(define index (load "views/index.xml.scm"))
;; (define index (quote (html (body (h1 "bus scheme") ) ) ) )
;; (defresource "/" (quote (html (body (h1 "Bus Scheme") ) )))
(defresource "/" index) 
(webwait)
